---
title: "p8105_hw2_mra2209"
author: "Maya Arnott"
---

author: **Maya Arnott**   
date: **2025-09-19**

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tibble)
```

Importing pols-month data set:
```{r}
pols_df = (
  read_csv("fivethirtyeight_datasets/pols-month.csv") |> 
    janitor::clean_names()
)

```

Importing unemployment.csv data set:
```{r}
unemployment_df = (
  read_csv("fivethirtyeight_datasets/unemployment.csv") |> 
    janitor::clean_names()
)
```

Importing snp.csv data set:
```{r}
snp_df = (
  read_csv("fivethirtyeight_datasets/snp.csv") |> 
    janitor::clean_names()
)
```

Cleaning the data in pols_df:
```{r}
pols_df <- pols_df |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    year = as.integer(year),
    month = month.name[as.integer(month)],
    day = as.integer(day),
    president = case_when(
      prez_dem == 1 ~ "dem",
      prez_gop == 1 ~ "gop",
      TRUE ~ NA_character_  # to get rid of any missing values
    )
  ) |> 
  select(-prez_dem, -prez_gop, -day) #drops old columns
```

Cleaning the data in snp_df:
```{r}
snp_df <- snp_df |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  mutate(
    year = as.integer(year),
    month = month.name[as.integer(month)],
    day = as.integer(day),
    year = ifelse(year < 50, year + 2000, year + 1900),
  ) |> 
  select(-day) |>  # drops old column
  select(year, month, close)
```

Cleaning the data in unemployment_df:
```{r}
unemployment_df <- unemployment_df |> 
  pivot_longer(
    cols = jan:dec,      # pivot these columns
    names_to = "month",  # new name is "month"
    values_to = "unemployment (%)"  # new column is for the values
  )
```

